const fs = require('fs');
const c = fs.readFileSync('server.js', 'utf8');
console.log('Direct pool usage:', c.includes('pool.'));
console.log('Uses getAll:', c.includes('getAll('));
console.log('Uses create:', c.includes('create('));
console.log('Uses update:', c.includes('update('));
console.log('Uses remove:', c.includes('remove('));
console.log('Has { Pool } import:', c.includes('const { Pool }'));
console.log('Has pool import:', c.includes("const pool = require('./db/pool')"));
console.log('Has express-rate-limit:', c.includes('express-rate-limit'));
console.log('Uses loginRateLimit:', c.includes('loginRateLimit'));
console.log('Uses corsMiddleware:', c.includes('corsMiddleware'));
console.log('Uses authenticateToken:', c.includes('authenticateToken'));
console.log('Uses requireRole:', c.includes('requireRole'));
console.log('Uses requireSelfOrAdmin:', c.includes('requireSelfOrAdmin'));
console.log('Uses optionalAuth:', c.includes('optionalAuth'));
console.log('Has /api/health:', c.includes("/api/health'"));
console.log('Has /api/auth/login:', c.includes("/api/auth/login'"));
console.log('Has /api/auth/register:', c.includes("/api/auth/register'"));
console.log('Has /api/auth/me:', c.includes("/api/auth/me'"));
console.log('Has /api/drives:', c.includes("/api/drives'"));
console.log('Has /api/drives/eligible:', c.includes("/api/drives/eligible'"));
console.log('Has /api/registrations:', c.includes("/api/registrations'"));
console.log('Has /api/students:', c.includes("/api/students'"));
console.log('Has /api/students/me:', c.includes("/api/students/me'"));
console.log('Has /api/dashboard/stats:', c.includes("/api/dashboard/stats'"));
console.log('Has /api/companies:', c.includes("/api/companies'"));
console.log('Has /api/schedules:', c.includes("/api/schedules'"));
console.log('Has /api/notifications:', c.includes("/api/notifications'"));
console.log('Has /api/activity-log:', c.includes("/api/activity-log'"));
console.log('Has /api/reports/stats:', c.includes("/api/reports/stats'"));
console.log('Has /api/reports/registrations:', c.includes("/api/reports/registrations'"));
console.log('Has /api/reports/company-wise:', c.includes("/api/reports/company-wise'"));
console.log('Has /api/applications:', c.includes("/api/applications'"));
console.log('Has /api/students/:id/applications:', c.includes("/api/students/:id/applications'"));
console.log('Has /api/students/:id/drives:', c.includes("/api/students/:id/drives'"));
console.log('Has /api/admin/registered-students:', c.includes("/api/admin/registered-students'"));
console.log('Has /api/drives/:id/eligibility:', c.includes("/api/drives/:id/eligibility'"));
console.log('Has /api/drives/:id/register:', c.includes("/api/drives/:id/register'"));
console.log('Has /api/registrations/:id/status:', c.includes("/api/registrations/:id/status'"));
console.log('Has /api/registrations/bulk-shortlist:', c.includes("/api/registrations/bulk-shortlist'"));
console.log('Has /api/registrations/bulk-reject:', c.includes("/api/registrations/bulk-reject'"));
console.log('Has /api/registrations/:id (DELETE):', c.includes("app.delete('/api/registrations/:id'"));
console.log('Has /api/companies/sync/overview:', c.includes("/api/companies/sync/overview'"));
console.log('Has /api/companies/:id/sync/preview:', c.includes("/api/companies/:id/sync/preview'"));
console.log('Has /api/companies/:id/sync/approve:', c.includes("/api/companies/:id/sync/approve'"));
console.log('Has /api/drives/:id/status:', c.includes("/api/drives/:id/status'"));
console.log('Has /api/drives/:id/duplicate:', c.includes("/api/drives/:id/duplicate'"));
console.log('Has /api/schedules/my:', c.includes("/api/schedules/my'"));
console.log('Has /api/notifications/read-all:', c.includes("/api/notifications/read-all'"));
console.log('Has /api/notifications/:id/read:', c.includes("/api/notifications/:id/read'"));
console.log('Has /api/students/:id (PUT):', c.includes("app.put('/api/students/:id'"));
console.log('Has /api/students/me/dashboard:', c.includes("/api/students/me/dashboard'"));
console.log('Has /api/dashboard/charts:', c.includes("/api/dashboard/charts'"));
console.log('Has /api/skills/normalize:', c.includes("/api/skills/normalize'"));
console.log('Total lines:', c.split('\n').length);
